layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: stavroskalapothas  
  keybase: stevaras
  linkedin: skalapothas
  # mastodon: your_username
  medium: stavrosk
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: stavros_it
  # unsplash: your_username
  # vk: your_username
  website: https://ubinet.gr
  youtube: istevaras

topics:
  - name: LPWAN
    web_url: https://en.wikipedia.org/wiki/LPWAN
    image_url: https://raw.githubusercontent.com/Stavros/stavros.github.io/master/assets/LPWAN-Logos.png

  - name: IoT
    web_url: https://www.internet-der-dinge.de/en.html
    image_url: https://raw.githubusercontent.com/Stavros/stavros.github.io/master/assets/internet-of-things-world.png

  - name: M2M
    web_url: https://www.etsi.org/technologies/internet-of-things
    image_url: https://raw.githubusercontent.com/Stavros/stavros.github.io/master/assets/m2m.png

  - name: GNURadio
    web_url: https://www.gnuradio.org/
    image_url: https://raw.githubusercontent.com/Stavros/stavros.github.io/master/assets/gnuradio-logo.png
    
  - name: FPGA
    web_url: https://en.wikipedia.org/wiki/Field-programmable_gate_array
    image_url: https://raw.githubusercontent.com/Stavros/stavros.github.io/master/assets/Fpga.png